### ISSUE TITLE
Link not working (404 error)

### ISSUE THREAD

**Issue by podgek** [IBM/spm-kubernetes#68] opened 2021-04-22 16:37 UTC
The "Configuration Reference" link on this page results in a 404 Not Found error: https://ibm.github.io/spm-kubernetes/deployment/hc_preparation

It attempts to link to: https://ibm.github.io/spm-kubernetes/config-reference

**Comment by andreyzher** [comment] 2021-04-22 16:44
Hi @podgek 

That's strange, our link-checker isn't reporting any errors.

I see 4 instances of the text "Configuration Reference" on that page, and all seem to point to the correct location:
https://ibm.github.io/spm-kubernetes/deployment/config-reference

Could you try a different browser or an incognito session to make sure there isn't something in cookies preventing correct routing of those links?

Thanks

**Comment by podgek** [comment] 2021-04-22 16:53
That is not what I am seeing. The two in-page links are pointing me at the broken link.

**Comment by podgek** [comment] 2021-04-22 16:55
Perhaps I had an old page in my cache or something. Looks like either the links were fixed just now, or a forced refresh picked up changes from somewhere. All good now.

**Comment by podgek** [comment] 2021-04-22 16:55
Fixed, or not a problem

**Comment by podgek** [comment] 2021-04-22 17:10
Reopened as reproduced the problem within my Fyre VM and on my local machine, and on multiple browsers.

If I click the "Preparing Helm Charts" link in the index on the lefthand side, and then click either of those in page links, I get the 404 error. If I then go directly to that same URL that is linked to from the index, then it works. I've tried in incognito mode and multiple browsers too.

Steps to reproduce:
Go here: https://ibm.github.io/spm-kubernetes
Click "Deploying with Helm Charts"
Click "Preparing Helm Charts"
Scroll down and click either of the in page links: "Configuration Reference".
I get the 404 error.

If I go direct to "https://ibm.github.io/spm-kubernetes/deployment/hc_preparation/" those links work fine.

The only difference I see is that when I go to that link from the index it goes to: "https://ibm.github.io/spm-kubernetes/deployment/hc_preparation", so missing the last slash.

**Comment by andreyzher** [comment] 2021-04-22 17:36
Yep, I was able to reproduce too the moment you had closed the issue. The navigation without the trailing slash seems unreliable, because I was definitely able to view the page without the trailing slash...
Thanks for bringing this to our attention.

**Comment by andreyzher** [comment] 2021-04-29 12:11
This issue has been resolved in our [April release](https://github.com/IBM/spm-kubernetes/releases/tag/21.4.0).

**Closed by andreyzher** 2021-04-29 12:11 UTC
