### ISSUE TITLE
helm install fails waiting for response

### ISSUE THREAD

**Issue by parmarpIBM** [IBM/spm-kubernetes#37] opened 2020-10-06 20:34 UTC
The runbook step to execute helm install using 

helm install releasename local-development/spm

is failing on a timeout.  There doesn't appear to be detailed logs I can find.  Please see the attached screenshot of the dashboard.  it shows a timeout event on the customsql job.   However, when I Execute a curl command from the command line I get a response immediately. 

[ibmadmin@localserver helm-charts]$ curl http://minikube.local:5000/v2
`<a href="/v2/">Moved Permanently</a>.`

If I attempt to install again, I get this error message. 

[ibmadmin@localserver helm-charts]$ helm install spm-v1 local-development/spm
Error: cannot re-use a name that is still in use

Please advise.

![image](https://user-images.githubusercontent.com/72471459/95256561-d5b98380-07d7-11eb-95ef-220fc14c88d5.png)

**Comment by andreyzher** [comment] 2020-10-06 21:35
Hi,

Please confirm that the Minikube VM has been configured as per our [guide](https://ibm.github.io/spm-kubernetes/prereq/kubernetes/minikube/#starting-minikube), specifically setting the `--insecure-registry` and `--memory` flags?

```
minikube start --vm-driver=virtualbox --cpus 4 --memory 8G \
         --insecure-registry "192.168.0.0/16" --disk-size='30G' --kubernetes-version v1.18.6
```

From your screenshot, it appears that the pod is attempting to reach the Minikube registry using HTTPS, whereas it should be using HTTP (i.e. insecure registry).

If the IP of your Minikube environment was generated in a different subnet, you may need to adjust your start command.

Run `minikube ip` to check if your environment is using the `192.168.0.0/16` range (e.g. `192.168.99.100`). If not, you will need to re-create the minikube cluster setting the `--insecure-registry` flag accordingly.

**Comment by parmarpIBM** [comment] 2020-10-06 22:38
Good catch on the https.  Here are the commands I used.  I used 6 GB because I'm running this inside a VM where the whole VM is allocated 8 GB.

`[ibmadmin@localserver helm-charts]$ minikube start --vm-driver=docker --cpus 2 --memory 6G --insecure-registry "172.17.0.0/16" --disk-size='15G' --kubernetes-version v1.18.3`

`[ibmadmin@localserver helm-charts]$ minikube addons enable registry`

```
[ibmadmin@localserver helm-charts]$ minikube ip
172.17.0.4
```

```
[ibmadmin@localserver helm-charts]$ sudo echo -e "$(minikube ip)\tminikube.local" | sudo tee -a /etc/hosts
172.17.0.4	minikube.local
```

I deleted the cluster by executing minikube delete and then recreated it using these commands above.  However I get the same result you see in the screenshot.

Is there another setting for the https issue?

**Comment by andreyzher** [comment] 2020-10-07 12:14
I only notice now that you're also using the `docker` driver for Minikube, which appears to be a contributing factor to the documented commands not working quite as expected - the runbook was only validated with Minikube using VirtualBox and VMware Fusion drivers.

I was able to reproduce your issue using an image from the [Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) docs:

```
docker pull k8s.gcr.io/echoserver:1.4
docker tag k8s.gcr.io/echoserver:1.4 minikube.local:5000/echoserver:1.4
docker push minikube.local:5000/echoserver:1.4

kubectl create deployment hello-node-1 --image=minikube.local:5000/echoserver:1.4
kubectl create deployment hello-node-2 --image=localhost:5000/echoserver:1.4
```

The pod for `hello-node-1` gets stuck with an ImagePullBackOff error.
The pod for `hello-node-2` is created successfully.

The implementation of the `docker` driver isn't able to resolve that test domain in some instances, and when it does, it's in a different internal IP range that what is specified in the `--insecure-registry` flag.

Please update your override values file to refer to `localhost:5000` instead of `minikube.local:5000` for pulling images

```
global:
  images:
    registry: localhost:5000
```

**Comment by parmarpIBM** [comment] 2020-10-07 17:40
Thanks Andrey.  That worked.  I am able to pull the image now. 

However, it hit another error related to DB2.  I'll open another issue on that one.

**Comment by andreyzher** [comment] 2020-10-07 17:45
Great, thanks for confirming. I'll close this since this specific problem is resolved.

**Closed by andreyzher** 2020-10-07 17:45 UTC
